routes/web.php
<?php

use App\Http\Controllers\Account\UserController;
use App\Http\Controllers\Admin\BoardController;
use App\Http\Controllers\Admin\ProductsController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Ajax\RemoveImageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::delete('ajax/images/{image_id}', RemoveImageController::class)
    ->middleware(['auth', 'admin'])
    ->name('ajax.products.images.delete');

// localhost/admin/.... route(admin.products)
Route::prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function() {
    Route::get('/', BoardController::class)->name('home');

    Route::resource('products', ProductsController::class)->except(['show']);
});

Route::prefix('account')->name('account.')->middleware(['auth'])->group(function() {
    Route::get('/', [UserController::class, 'index'])->name('main');
    Route::get('{user}/edit', [UserController::class, 'edit'])->middleware('can:view,user')->name('edit');
    Route::put('{user}', [UserController::class, 'update'])->name('update'); // TODO: ->middleware('can:update,user')
});

Route::resource('categories', CategoriesController::class)->only(['show', 'index']);
Route::resource('products', \App\Http\Controllers\ProductsController::class)->only(['show', 'index']);
Route::get('cart', [CartController::class, 'index'])->name('cart');
Route::post('cart/{product}', [CartController::class, 'add'])->name('cart.add');
Route::delete('cart', [CartController::class, 'remove'])->name('cart.remove');
Route::post('cart/{product}/count', [CartController::class, 'countUpdate'])->name('cart.count.update');

Route::middleware('auth')->group(function() {
    Route::get('checkout', \App\Http\Controllers\CheckoutController::class)->name('checkout');
    Route::post('order', \App\Http\Controllers\OrdersController::class)->name('order.create');
});

app/Http/Controllers/CartController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Http\Request;

class CartController extends Controller
{
    public function index()
    {
        return view('cart/index');
    }

    public function add(Request $request, Product $product)
    {
        $cartItem = Cart::instance('cart')->add(
            $product->id,
            $product->title,
            $request->product_count,
            $product->end_price
        );

        $cartItem->associate(Product::class);

        return redirect()->back()->with('success', 'The product was added into the cart');
    }

    public function remove(Request $request)
    {
        Cart::instance('cart')->remove($request->rowId);
        return redirect()->back();
    }

    public function countUpdate(Request $request, Product $product)
    {
        if ($product->in_stock < $request->product_count) {
            return redirect()->back()
                ->with('warn', 'The product [' . $product->title . '] has only ' . $product->in_stock . ' items');
        }

        Cart::instance('cart')->update(
            $request->rowId,
            $request->product_count
        );

        return redirect()->back();
    }
}

resources/views/cart/parts/product_view.blade.php
<tr>
    <td>
        <img src="{{ Storage::url($row->model->thumbnail) }}" height="100" alt="">
    </td>
    <td>
        <a href="{{ route('products.show', $row->id) }}"><strong>{{ $row->name }}</strong></a>
        {{--        <p>{{ ($row->options->has('size') ? $row->options->size : '') }}</p>--}}
    </td>
    <td>
        <form action="{{ route('cart.count.update', $row->id) }}" method="POST">
            @csrf
            <input type="hidden" value="{{ $row->rowId }}" name="rowId">
            <input type="number"
                   min="1"
                   value="{{ $row->qty }}"
                   max="{{ $row->model->in_stock }}"
                   name="product_count"
            >
            <input type="submit" class="btn btn-outline-success" value="Update count">
        </form>
    </td>
    <td>{{ $row->price }}$</td>
    <td>{{ $row->subtotal }}$</td>
    <td>
        <form action="{{ route('cart.remove') }}" method="POST">
            @csrf
            @method('DELETE')
            <input type="hidden" value="{{ $row->rowId }}" name="rowId">
            <input type="submit" class="btn btn-outline-danger" value="{{ __('Delete') }}">
        </form>
    </td>
</tr>